version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - cdk synth
  post_build:
    commands:
      - cdk deploy --require-approval never
